[package]
name = "dsekdocs"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = [ "D-sektionen inom TLTH" ]
license = "MIT"
homepage = "dsek.se"
repository = "https://github.com/Dsek-LTH/dsekdocs"
categories = [ ]
disciplines = [ ]
