#!/bin/sh

set -eu

about='
This script is a wrapper around the typst command that facilitates compiling files in this repo. It is not (yet) designed for compiling files outside it. If you wish to do so, you should pass the --root flag.
'

if [ "$#" = 0 ]; then
    echo "$about" | fold -s >&2
fi

ROOT="$(dirname "$0")"

root=
font=

for argument in "$@"; do
    case "$argument" in
    c | compile | w | watch)
        root="--root $ROOT"
        font="--font-path $ROOT/fonts"
        ;;
    -h | --help | help)
        echo "$about" | fold -s >&2
        ;;
    --root) root= ;;
    --font-path) root= ;;
    esac
done

# shellcheck disable=SC2086
exec typst "$@" $root $font
