[package]
name = "dsek"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = [ "D-sektionen inom TLTH" ]
license = "MIT"
homepage = "dsek.se"
repository = "https://github.com/Dsek-LTH/dsek-typst"
categories = [ ]
disciplines = [ ]
