#!/bin/sh

set -eu

cd "$(dirname "$0")/.."

echo 'Building the examples...' >&2

for example in examples/*.typ; do
    echo "  Compiling $example..." >&2

    tools/typstw compile "$example"
done

echo '...done!' >&2
