#!/bin/sh

set -eu

cd "$(dirname "$0")/.."

echo 'Building the documentation...' >&2

cp -f docs/preamble.typ docs/main.typ

echo '  Inserting modules...' >&2

# We ignore `../src/lib.typ` since we want it sorted first.
# Since we split on a newline, any file names containing newlines will break the script.
# The %d, sort, cut chain is to sort shallower file paths first.
find src \
    -name '*typ' -not -path src/lib.typ \
    -printf '%d %p\n' |
    sort -n |
    cut -d' ' -f2- |
    sed 's/.*/#document-module("&")/g' >>docs/main.typ

echo '  Compiling to PDF...' >&2

# TODO: Split up documentation pdfs between documents and util functions
# I think most people using this are more likely to want to know what templates
# there are, and which parameters go with which template.
# But of course we still need to provide documentation for the util functions for
# people who want more flexibility in their writing, and future package maintainers

tools/typstw compile main.typ

echo '...done!' >&2
