#!/bin/sh

# TODO: Remove this script when we gen an actual test suite (like Tytanic) set up.

set -eu

cd "$(dirname "$0")/.."

tools/build-docs
tools/build-examples

echo 'Compiling the files in src...'
find src -name '*.typ' \
    -exec printf '  Compiling %s...\n' {} ';' \
    -exec tools/typstw compile {} ';'
echo '...done!'
